version: "3"
services:
  db:
    image: mysql
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - gesprendercoreframework
  php:
    build: ./docker/.
    container_name: PHP8.2
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - gesprendercoreframework
  phpmyadmin:
    image: phpmyadmin
    container_name: PHPMyAdmin
    ports:
      - 3001:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=MySQL
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - gesprendercoreframework
  redis:
    image: redis
    container_name: RedisContainer
    ports:
      - 6379:6379
    networks:
      - gesprendercoreframework
  postgres:
    image: postgres
    container_name: PostgreSQL
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_DB: "POSTGRES_DB"
      POSTGRES_USER: "POSTGRES_USER"
      POSTGRES_PASSWORD: "POSTGRES_PASSWORD"
      POSTGRES_ROOT_PASSWORD: "POSTGRES_PASSWORD"
    volumes:
      - "./docker/postgresql:/var/lib/postgresql/data"
    networks:
      - gesprendercoreframework
  phpgadmin:
    image: dpage/pgadmin4
    container_name: PHPgAdmin
    ports:
      - 3002:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=jorgeemilianom@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=POSTGRES_PASSWORD
    networks:
      - gesprendercoreframework
    depends_on:
      - postgres
networks:
  gesprendercoreframework:
    name: gesprendercoreframework
    driver: bridge